trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'vedanttrivedi/flask-demo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - script: |
        echo "This is job Foo."
        echo "##vso[task.setvariable variable=doThing;isOutput=true]Yes" #The variable doThing is set to true
      name: DetermineResult
      
    - script: echo $(DetermineResult.doThing)
      name: echovar

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    condition: eq(stageDependencies.Build.Build.outputs['DetermineResult.doThing'], 'Yes') #map doThing and check if true
    
    pool: Default 
    
    variables:
      varFromStageA: $[ stageDependencies.Build.Build.outputs['DetermineResult.doThing'] ]
    steps:
    - bash: echo "Hello world stage  From DEploy stage job"
    - script: echo $(varFromStageA)