trigger:
- main
 
resources:
- repo: self
 
variables:
  tag: '$(Build.BuildId)'
 
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    
    variables:
      vversion : 10
    displayName: Build
    pool:
      vmImage : ubuntu-latest
    steps:
    - script: |
        name="vedant"
        echo "my name is $name and version is $vversion and with brackets $(vversion)"
        echo "variable from variable vversion is $(vversion)"
        echo "##vso[task.setvariable variable=version;isOutput=true]$name"
      name: DefineVersion
      
 
- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool: 
      vmImage : ubuntu-latest

    variables:
      buildVariable: $[ stageDependencies.Build.Build.outputs['DefineVersion.version'] ]
    steps:
    - script: echo "Using variable define in build stage $(buildVariable)"