trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - script: |
        echo "##vso[task.setvariable variable=version;isOutput=true]1.1.1"
      name: DefineVersion
    - script: |
        echo "##vso[task.setvariable variable=versions;isOutput=true]$[ stageDependencies.Build.Build.outputs['DefineVersion.version']]"
      name: DynamicVersion
    - script: |
        echo "Accessing dynamic version ${DynamicVersion.versions}"
      name: AccessDynamicVersion
      

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool: Default 
    
    variables:
      buildVariable: $[ stageDependencies.Build.Build.outputs['DefineVersion.version'] ]
    steps:
    - script: echo "Using variable define in build stage $(buildVariable)"