trigger:
- main
 
resources:
- repo: self
 
variables:
  tag: '$(Build.BuildId)'
 
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    
    variables:
      vversion : 10
    displayName: Build
    pool: Default
    steps:
    - script: |
        echo "##vso[task.setvariable variable=version;isOutput=true]$vversion"
      name: DefineVersion
      
 
- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool: Default
    
    variables:
      buildVariable: $[ stageDependencies.Build.Build.outputs['DefineVersion.version'] ]
    steps:
    - script: echo "Using variable define in build stage $(buildVariable)"