# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
      
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'vedanttrivedi/flask-demo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'az login'
      
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'az container create --resource-group sa1_test_eic_VedantTrivedi --name myscontainerse --image vedanttrivedi/flask-demo:60 --dns-name-label vstlabs --ports 80'
    
      displayName: Create container instance and upload docker image