trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'vedanttrivedi/flask-demo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

    # Define a variable in the Build stage
    - bash: echo "##vso[task.setvariable variable=version]1.2.3"
      displayName: 'Set version'

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool: Default 
    steps:
    # Use the variable defined in the Build stage
    - script: echo "Hello"
      displayName: 'Use version'
# $(stageDependencies.Build.Build.outputs['Set version.version'])