trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool: Default
      
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'vedanttrivedi/flask-demo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

    # Define an output variable
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "##vso[task.setvariable variable=sampleVariable;isOutput=true]exampleValue"
      displayName: 'Set sampleVariable'

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool: Default
    steps:
    # Use the output variable defined in the Build stage
    - script: echo $(Build.Build.sampleVariable)
      displayName: 'Use sampleVariable'
