trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - script: echo "##vso[task.setvariable variable=version;isOutput=true]1.1.1"
      name: DefineVersion
    - script: |
        versions=$(DefineVersion.version)
        echo "variable in the dynamic version ${DefineVersion.version}"
        echo "##vso[task.setvariable variable=versions;isOutput=true]$versions"
      name: DynamicVersion
    - script: echo "Accessing dynamic version $(versions)"
      name: AccessDynamicVersion

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool: Default
    steps:
    - script: echo "Using variable defined in build stage $(versions)"
