trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  sampleVariable: 'exampleValue' # Define a sample variable

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
      
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'vedanttrivedi/flask-demo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

    # Set an output variable
    - script: echo "##vso[task.setvariable variable=outputVariable;isOutput=true]$(sampleVariable)"
      name: setOutputVar

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'

    # Reference the output variable from the build stage
    steps:
    - script: echo $(Build.Outputs.Build.setOutputVar)
      name: echoOutputVar
